# Generated by Django 5.1.15 on 2026-06-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('base_url', models.URLField()),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bike_stations', to='observations.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='RawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('request_url', models.URLField(max_length=500)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('body', models.JSONField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_payloads', to='observations.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('parse', 'Parse'), ('validation', 'Validation'), ('persistence', 'Persistence'), ('transport', 'Transport')], max_length=16)),
                ('error_type', models.CharField(max_length=128)),
                ('error_message', models.TextField()),
                ('record', models.JSONField(blank=True, null=True)),
                ('pydantic_errors', models.JSONField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dead_letters', to='observations.datasource')),
                ('raw_payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letters', to='observations.rawpayload')),
            ],
        ),
        migrations.CreateModel(
            name='BikeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('bikes_available', models.PositiveSmallIntegerField()),
                ('stands_available', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], max_length=8)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability', to='observations.bikestation')),
            ],
            options={
                'indexes': [models.Index(fields=['station', '-observed_at'], name='bikeavail_station_obs_idx'), models.Index(fields=['-observed_at'], name='bikeavail_obs_idx')],
                'constraints': [models.UniqueConstraint(fields=('station', 'observed_at'), name='uniq_bike_obs')],
            },
        ),
        migrations.AddIndex(
            model_name='bikestation',
            index=models.Index(fields=['latitude', 'longitude'], name='observation_latitud_c609f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='bikestation',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_bike_station'),
        ),
        migrations.AddIndex(
            model_name='rawpayload',
            index=models.Index(fields=['source', '-fetched_at'], name='observation_source__1b0934_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletter',
            index=models.Index(fields=['source', '-failed_at'], name='observation_source__a84c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='deadletter',
            index=models.Index(fields=['resolved', '-failed_at'], name='observation_resolve_006e4f_idx'),
        ),
    ]
