# Generated by Django 5.1.15 on 2026-06-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noise_sensors', to='observations.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='NoiseReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('laeq_db', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='observations.noisesensor')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('temp_c', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity', models.PositiveSmallIntegerField()),
                ('wind_speed_ms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('conditions', models.CharField(max_length=64)),
                ('raw', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weather_observations', to='observations.datasource')),
            ],
        ),
        migrations.AddIndex(
            model_name='noisesensor',
            index=models.Index(fields=['latitude', 'longitude'], name='observation_latitud_55a39e_idx'),
        ),
        migrations.AddConstraint(
            model_name='noisesensor',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_noise_sensor'),
        ),
        migrations.AddIndex(
            model_name='noisereading',
            index=models.Index(fields=['sensor', '-observed_at'], name='noise_sensor_obs_idx'),
        ),
        migrations.AddIndex(
            model_name='noisereading',
            index=models.Index(fields=['-observed_at'], name='noise_obs_idx'),
        ),
        migrations.AddConstraint(
            model_name='noisereading',
            constraint=models.UniqueConstraint(fields=('sensor', 'observed_at'), name='uniq_noise_obs'),
        ),
        migrations.AddIndex(
            model_name='weatherobservation',
            index=models.Index(fields=['-observed_at'], name='weather_obs_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatherobservation',
            constraint=models.UniqueConstraint(fields=('source', 'observed_at'), name='uniq_weather_obs'),
        ),
    ]
